context:
  environment: dev
connection:
    type: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres
schemas:
  - name: public
    description: Default schema
  - name: customer
    description: Customer schema
  - name: product
    description: Product schema