name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov

#    - name: Run linting
#      run: flake8 .

    - name: Run tests with coverage
      run: pytest --cov=./ --cov-report=xml

    - name: Check coverage threshold
      run: |
        coverage_percentage=$(pytest --cov=./ --cov-report=term-missing | grep TOTAL | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$coverage_percentage < 80" | bc -l) )); then
          echo "Test coverage is below 80%. Current coverage: $coverage_percentage%"
          exit 1
        fi